name: Deploy Express Demo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull brando90/express-demo:latest
            docker stop express-demo || true
            docker rm express-demo || true
            docker run -d --name express-demo -p 3000:3000 brando90/express-demo:latest
